--Author : Generated by Omega Script Writer 1.0
--Purpose : add a new column to table
--Date : 22/08/2017 4:31:15 PM

If Exists (Select * From sysobjects Where name = 'Customer' and xtype ='U') 
Begin
           If not exists (select * from syscolumns col inner join sysobjects tab 
           On col.id = tab.id where tab.name =   'Customer'  and col.name = 'SaleMan1')
           Alter Table  Customer Add SaleMan1 int Null
End 
GO

If Exists (Select * From sysobjects Where name = 'Customer' and xtype ='U') 
Begin
           If not exists (select * from syscolumns col inner join sysobjects tab 
           On col.id = tab.id where tab.name =   'Customer'  and col.name = 'SaleMan2')
           Alter Table  Customer Add SaleMan2 int Null
End 
GO

If Exists (Select * From sysobjects Where name = 'Customer' and xtype ='U') 
Begin
           If not exists (select * from syscolumns col inner join sysobjects tab 
           On col.id = tab.id where tab.name =   'Customer'  and col.name = 'SaleMan3')
           Alter Table  Customer Add SaleMan3 int Null
End 
GO

If Exists (Select * From sysobjects Where name = 'Customer' and xtype ='U') 
Begin
           If not exists (select * from syscolumns col inner join sysobjects tab 
           On col.id = tab.id where tab.name =   'Customer'  and col.name = 'AttachFile')
           Alter Table  Customer Add AttachFile nvarchar(500) Null
End 
GO
